import 'package:flutter/material.dart';
import 'package:razorpay_flutter/razorpay_flutter.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../core/theme/app_theme.dart';
import '../../core/utils/formatters.dart';
import '../../models/payment_model.dart';
import '../../services/payment_service.dart';

class PaymentScreen extends StatefulWidget {
  const PaymentScreen({super.key, required this.dueId, required this.amount, required this.dueNumber});
  final String dueId;
  final num amount;
  final int dueNumber;

  @override
  State<PaymentScreen> createState() => _PaymentScreenState();
}

class _PaymentScreenState extends State<PaymentScreen> {
  final _paymentService = PaymentService();
  late final Razorpay _razorpay;

  bool _isLoading = false;
  String? _error;
  UpiIntent? _upiIntent;
  bool _awaitingConfirmation = false;
  bool _paymentConfirmed = false;

  @override
  void initState() {
    super.initState();
    _razorpay = Razorpay();
    _razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS, _onRazorpaySuccess);
    _razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, _onRazorpayError);
    _razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET, _onExternalWallet);
  }

  @override
  void dispose() {
    _razorpay.clear();
    super.dispose();
  }

  Future<void> _startPayment() async {
    setState(() {
      _isLoading = true;
      _error = null;
    });
    try {
      final result = await _paymentService.initiatePayment(
        dueId: widget.dueId,
        method: 'UPI',
        amount: widget.amount,
      );

      if (result.razorpayOrder != null) {
        // Real gateway path: open Razorpay Checkout with the order the
        // backend created. Razorpay itself notifies our backend via a
        // signature-verified webhook, which is the source of truth for
        // marking the due paid — the on-device callback below is only used
        // to give the customer immediate visual feedback.
        _openRazorpayCheckout(result.razorpayOrder!);
      } else if (result.upiIntent != null) {
        // Fallback path: static UPI-intent QR / deep link, confirmed
        // manually by an admin after checking the bank/UPI app.
        _upiIntent = result.upiIntent;
        setState(() => _awaitingConfirmation = true);
        final uri = Uri.parse(_upiIntent!.upiUrl);
        if (await canLaunchUrl(uri)) {
          await launchUrl(uri, mode: LaunchMode.externalApplication);
        }
      }
    } catch (e) {
      setState(() => _error = e.toString());
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  void _openRazorpayCheckout(RazorpayOrder order) {
    final options = {
      'key': order.keyId,
      'order_id': order.orderId,
      'amount': order.amount, // already in paise from the backend
      'currency': order.currency,
      'name': 'Finance App',
      'description': 'Due #${widget.dueNumber} repayment',
      'method': {'upi': true, 'card': false, 'netbanking': false, 'wallet': false},
    };
    try {
      _razorpay.open(options);
      setState(() => _awaitingConfirmation = true);
    } catch (e) {
      setState(() => _error = 'Could not open Razorpay checkout: $e');
    }
  }

  int? _billNumber;

  void _onRazorpaySuccess(PaymentSuccessResponse response) async {
    // The webhook (server-to-server, signature-verified) is what actually
    // marks the due as PAID — we don't trust this client callback alone.
    // We just reflect a "processing" state here for a good UX.
    setState(() => _paymentConfirmed = true);
    
    // Poll to get the bill number generated by the webhook
    for (int i = 0; i < 5; i++) {
      await Future.delayed(const Duration(seconds: 2));
      if (!mounted) break;
      try {
        final list = await _paymentService.listPayments();
        final payment = list.where((p) => p.dueId == widget.dueId).firstOrNull;
        if (payment != null && payment.billNumber != null) {
          setState(() => _billNumber = payment.billNumber);
          break;
        }
      } catch (_) {}
    }
  }

  void _onRazorpayError(PaymentFailureResponse response) {
    setState(() {
      _error = response.message ?? 'Payment failed or was cancelled.';
      _awaitingConfirmation = false;
    });
  }

  void _onExternalWallet(ExternalWalletResponse response) {
    setState(() => _awaitingConfirmation = true);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.surfaceLight,
      appBar: AppBar(
        backgroundColor: AppTheme.primaryColor,
        foregroundColor: Colors.white,
        title: Text('Pay Due #${widget.dueNumber}', style: const TextStyle(fontWeight: FontWeight.w700, color: Colors.white)),
      ),
      body: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                gradient: AppTheme.primaryGradient,
                borderRadius: BorderRadius.circular(24),
                boxShadow: [
                  BoxShadow(
                    color: AppTheme.primaryColor.withValues(alpha: 0.35),
                    blurRadius: 20,
                    offset: const Offset(0, 8),
                  ),
                ],
              ),
              child: Column(
                children: [
                  const Text(
                    'Amount Due',
                    style: TextStyle(color: Colors.white70, fontWeight: FontWeight.w500, fontSize: 13),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    Formatters.currency(widget.amount),
                    style: const TextStyle(fontSize: 32, fontWeight: FontWeight.w800, color: Colors.white, letterSpacing: 0.5),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    'Due #${widget.dueNumber}',
                    style: const TextStyle(color: Colors.white60, fontSize: 12),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 24),
            if (_error != null) ...[
              Text(_error!, style: const TextStyle(color: AppTheme.errorColor), textAlign: TextAlign.center),
              const SizedBox(height: 12),
            ],
            if (!_awaitingConfirmation) ...[
              ElevatedButton.icon(
                onPressed: _isLoading ? null : _startPayment,
                icon: const Icon(Icons.qr_code),
                label: _isLoading
                    ? const SizedBox(
                        height: 18, width: 18, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))
                    : const Text('Pay with UPI'),
              ),
              const SizedBox(height: 12),
              Text(
                'This opens UPI checkout to complete payment. Your due status updates automatically once payment is confirmed.',
                style: TextStyle(color: Colors.grey.shade600, fontSize: 13),
                textAlign: TextAlign.center,
              ),
            ] else if (_paymentConfirmed) ...[
              const Icon(Icons.check_circle_outline, size: 48, color: AppTheme.successColor),
              const SizedBox(height: 12),
              Text(
                _billNumber != null 
                  ? 'Payment received! Bill No: $_billNumber' 
                  : 'Payment received! Generating bill number...',
                textAlign: TextAlign.center,
                style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 16),
              ),
              const SizedBox(height: 8),
              const Text(
                'It may take a few moments to reflect completely — pull to refresh on the loan screen.',
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: () => Navigator.pop(context),
                child: const Text('Back to Loan'),
              ),
            ] else ...[
              const Icon(Icons.hourglass_top_outlined, size: 48, color: AppTheme.accentColor),
              const SizedBox(height: 12),
              const Text(
                'Payment initiated. Once confirmed, this due will be marked as paid and you\'ll get a receipt.',
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 20),
              OutlinedButton(
                onPressed: () => Navigator.pop(context),
                child: const Text('Back to Loan'),
              ),
            ],
          ],
        ),
      ),
    );
  }
}
